
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TaskManagerAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProjectUser()
    {

        this.TaskDetails = new HashSet<TaskDetail>();

    }


    public int User_ID { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public int Employee_ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TaskDetail> TaskDetails { get; set; }

}

}
