
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TaskManagerAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TaskDetail
{

    public int Task_ID { get; set; }

    public string Task_Name { get; set; }

    public string Parent_Task_Name { get; set; }

    public System.DateTime Start_date { get; set; }

    public System.DateTime End_Date { get; set; }

    public int Task_Priority { get; set; }

    public string ISTaskEnded { get; set; }

    public Nullable<int> User_ID { get; set; }

    public Nullable<int> Project_ID { get; set; }



    public virtual ProjectDetail ProjectDetail { get; set; }

    public virtual ProjectUser ProjectUser { get; set; }

}

}
